### ISSUE TITLE
Dataset science keywords is not usable

### ISSUE THREAD

**Issue by cnrdh** [npolar/data.npolar.no#40]
It should not limit search to only 10 matches.
It should exclude the lower levels of the hierarchy by default (filter by cardinality)

Now it's impossible for example to set
EARTH SCIENCE > BIOLOGICAL CLASSIFICATION > ANIMALS/INVERTEBRATES

because the autcomplete gives 10 "random" results at even lower levels....

**Comment by Stastein** [comment]
There are usability issues here too. We have to give the users some clues to the keyword search, otherwise the GCMD jungle is non-navigable.
