### ISSUE TITLE
Breadcrumb with errors

### ISSUE THREAD

**Issue by srldl** [npolar/data.npolar.no#65]
Needs to be fixed or simply removed. One option could be to keep "home" and the id only.

**Comment by baelter** [comment]
![screenshot from 2015-02-16 14 30 51](https://cloud.githubusercontent.com/assets/1399369/6212750/d2d7d35c-b5e8-11e4-91b9-b695cf0a6ca0.png)

**Comment by rexso** [comment]
Partially fixed with JavaScript
