### ISSUE TITLE
Avoid URLs as link text on internal links

### ISSUE THREAD

**Issue by paulflakstad** [npolar/data.npolar.no#82]
See e.g. this publication: https://data.npolar.no/publication/c83a3185-cf50-45be-8d40-43a9950ca90d and note that the project link is internal (points to a project entry in the data centre).

Problem:
Users have no idea what project that is; the link text is just a URL.

Proposed solution:
Use the project's title as link text.

*Note that this is relevant for other link types as well, not just project links on publications.*

Meaningful titles are of course already supported via the individual links' <code>title</code> field. However, manually entering titles on individual internal links is both unnecessary and guaranteed to cause inconsistency over time, and thus should probably be avoided if possible.

**Comment by cnrdh** [comment]
Agreed, but editor's responsibility
